# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a6ef51d04a124ec2a6dee613070ea5e12dfd514f22b5ee2cada0c41c27a34f96e09fecfffbbc90a4ac02a0739a4288a0840eb3868c3f7924895358334a7e334

test:
  secret_key_base: 627e48847f893095291b44d22792f707b6a25684d3ba214f96eb7f7c84070677df5f1cc24f0105165d266e1c90921bf8deb164586242174e1947fd6b515fbe39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
